global:
  scrape_interval: "5s"

scrape_configs:
  - job_name: "skins-cs2-api-API"
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    scheme: http
    follow_redirects: true
    body_size_limit: "0"
    sample_limit: 0
    label_limit: 0
    label_name_length_limit: 0
    label_value_length_limit: 0
    target_limit: 0
    static_configs:
      - targets: ["api:5000"]